---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.0/manifests/install.yaml
- https://github.com/argoproj-labs/argocd-image-updater//manifests/base/rbac?ref=v0.12.0
- https://github.com/argoproj-labs/argocd-image-updater//manifests/base/deployment?ref=v0.12.0
