apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: loki
        image: grafana/loki:1.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3100
          name: http
        volumeMounts:
        - name: data
          mountPath: /var/lib/loki
        - name: config
          mountPath: /etc/loki
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          allowPrivilegeEscalation: false
      volumes:
      - name: config
        secret:
          secretName: loki-config
      - name: data
        persistentVolumeClaim:
          claimName: loki
