---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rahla
spec:
  template:
    spec:
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"    
      containers:      
      - image: datatactics/theia:latest
        name: theia
        env:
        - name: PROJECTDIR
          value: "/deploy"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP                
---
apiVersion: v1
kind: Service
metadata:
  name: rahla
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---