---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole:1.4.0
        env:
          - name: GUACD_HOSTNAME
            value: "guacd"
          - name: GUACD_PORT
            value: "4822"
          - name: GUACAMOLE_HOME
            value: "/etc/guacamole/"  

        envFrom:
        - configMapRef:
            name: guacamole-env            
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: guacamole-conf
          mountPath: /etc/guacamole/          
#        livenessProbe:
#          httpGet:
#            path: /guacamole/
#            port: 8080
#          initialDelaySeconds: 45
#          timeoutSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /guacamole/
#            port: 8080
#          initialDelaySeconds: 2
#          timeoutSeconds: 10
      volumes:
        - name: guacamole-conf 
          configMap:
            name: guacamole-conf  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacd:1.4.0
        ports:
        - name: http
          containerPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    app: guacamole
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  labels:
    app: guacd
spec:
  ports:
  - port: 4822
    protocol: TCP
  selector:
    app: guacd
