apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
#        image: scheller.es:5443/amiga23/gitea-aarch64:1.11.6
        image: gitea/gitea:1.17.2
        imagePullPolicy: IfNotPresent
#        command: ["/bin/sh"]
#        args: ["-c", "while true; do echo hello; sleep 999;done"]
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: git
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitea
