apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: tks-tools
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
