apiVersion: v1
kind: Service
metadata:
  name: rawfile-csi-controller
  labels:
    app: rawfile-csi
    component: controller
spec:
  type: ClusterIP
  selector:
    app: rawfile-csi
    component: controller
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rawfile-csi-controller
spec:
  replicas: 1
  serviceName: rawfile-csi
  selector:
    matchLabels: &selectorLabels
      app: rawfile-csi
      component: controller
  template:
    metadata:
      labels: *selectorLabels
    spec:
      serviceAccount: rawfile-csi-driver
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: socket-dir
          emptyDir: {}
      containers:
        - name: csi-driver
          image: docker.io/openebs/rawfile-localpv:0.5.0
          imagePullPolicy: IfNotPresent
          args:
            - csi-driver
            - --disable-metrics
          env:
            - name: PROVISIONER_NAME
              value: rawfile.csi.openebs.io
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: IMAGE_REPOSITORY
              value: docker.io/openebs/rawfile-localpv
            - name: IMAGE_TAG
              value: 0.5.0
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - name: csi-probe
              containerPort: 9808
          resources:
                limits:
                  cpu: 1
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 100Mi
        - name: external-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: external-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
