apiVersion: v1
kind: Service
metadata:
  name: rawfile-csi-node
  labels:
    app: rawfile-csi
    component: node
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    app: rawfile-csi
    component: node
