apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rawfile-xfs
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  fsType: xfs
