apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.networking.k8s.io_gatewayclasses.yaml
- gateway.networking.k8s.io_gateways.yaml
- gateway.networking.k8s.io_httproutes.yaml
- gateway.networking.k8s.io_tcproutes.yaml
- gateway.networking.k8s.io_tlsroutes.yaml
- traefik.containo.us_ingressroutes.yaml
- traefik.containo.us_ingressroutetcps.yaml
- traefik.containo.us_ingressrouteudps.yaml
- traefik.containo.us_middlewares.yaml
- traefik.containo.us_middlewaretcps.yaml
- traefik.containo.us_serverstransports.yaml
- traefik.containo.us_tlsoptions.yaml
- traefik.containo.us_tlsstores.yaml
- traefik.containo.us_traefikservices.yaml
