# Run forward-auth.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-auth
spec:
  selector:
    matchLabels:
      app: forward-auth
  template:
    metadata:
      labels:
        app: forward-auth
    spec:
      containers:
      - name: forward-auth
        image: thomseddon/traefik-forward-auth:latest
        # thomseddon/traefik-forward-auth:2.2.0
        ports:
        - containerPort: 4181
