apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dex-server
  name: dex-server
spec:
  ports:
  - name: http
    port: 5556
    protocol: TCP
    targetPort: 5556
  - name: grpc
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: metrics
    port: 5558
    protocol: TCP
    targetPort: 5558
  selector:
    app: dex-server
  sessionAffinity: None
  type: ClusterIP
