apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: promtail
  name: promtail
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pods
    verbs:
    - get
    - watch
    - list
