---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200
    name: tempo
  - port: 14268
    targetPort: 14268
    name: jaeger
